[tool.black]
line-length = 119
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
    /(
    |\.git
    |\.idea
    |\bin
    |\include
    |\lib
    |\.mypy_cache
    |.\pytest_cache
    |\share
    |\.tox
    |\.venv)/
    | migrations
)
'''
